[project]
name = "ef-fastapi"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.13.4"
dependencies = [
    "common-lib[fastapi]",
    "fastapi[standard]==0.116.0",
    "pydantic==2.11.7",
]

[tool.uv.sources]
common-lib = { path = "src/common_lib" }
